### ISSUE TITLE
Material icons are not displayed

### ISSUE THREAD

**Issue by dwphk** [cintaccs/DynamicAI-Issues#2]
Bob from DataAccess installed v7 on an upgraded Windows7 machine with other systems installed as well - somehow he doesn’t see the material icon fonts - he sees the caption of the icon instead. I am rather sure it is because his IIS is not serving woff files (used for the icon font) - I know Balazs and I had the issue ones - but can’t find it at the moment - which IIS xml file should be modified to allow serving the font files?

or is there a way to trust the site so Chrome recognise it as trusted for font download..?

can you investigate - check in issue tracker closed items / old mails (Karoly you must have it somewhere)

**Comment by dwphk** [comment]
see attached pic - he also seems to have the font issue

2 users are having it now

Best regards,
Carsten




Start på videresendt besked:

> Fra: Bob Cergol <bob.cergol@dataaccess.com>
> Dato: 21. april 2017 kl. 08.45.45 GMT-4
> Til: Carsten Sørensen <cs@cintac.com>
> Cc: Eddy Kleinjan <eddy.kleinjan@dataaccess.eu>
> Emne: FW: Dynamic AI version 7 pre-release
>
> No surprise to me. Albin is not using a virgin Win10 VM on a Mac like you guys.
>
>  
>
> I told him you neither you or Eddy had this problem but were aware some others did, and said you’d probably have the solution in about a week.
>
> From: Albin Wisén [mailto:albin@prosmart.se]
> Sent: Friday, April 21, 2017 2:51 AM
> To: Bob Cergol
> Subject: SV: Dynamic AI version 7 pre-release
>
>  
>
> Bob,
>
>  
>
> Quick question. Is this something expected right now or do I miss a css file or something after the Install?
>
> I have no design at the menus. (attached picture).
>
>  
>
> Best regards
>
> Albin Wisén
>
>  
>
> logo 
>
> Prosmart System AB | Industrigatan 44B | 571 38 Nässjö
>
> Phone: +46 380-60 00 60 | Cell: +46 72-303 25 36
>
> albin@prosmart.se
>
> www.prosmart.se
>
>  
>
> Från: Bob Cergol [mailto:bob.cergol@dataaccess.com]
> Skickat: den 20 april 2017 20:36
> Till: Albin Wisén <albin@prosmart.se>
> Ämne: Dynamic AI version 7 pre-release
>
>  
>
> Hi Albin,
>
>  
>
> This is to follow-up on your forum post regarding availability of V7 pre-release.
>
>  
>
> You can download the install program for the pre-release alpha version of Dynamic AI V7 using your DataAccess Global User ID and this link:
>
>  
>
> https://www.dataaccess.eu/resources/downloads/download-category/download-subcategory/download-item-781?dagadi=DAISERVER7.0pr1
>
>  
>
> A few things you should know:
>
>  
>
>     Carsten hopes to release monthly updates to this alpha version after May. (They will still be alpha.)
>
>  
>
>     Please do not use the DAW DAI forum to report issues or ask questions about this pre-release version; Cintac has instead asked us to use this public GitHub issues list: https://github.com/cintaccs/DynamicAI-Issues/issues -- or I guess you could also use DAE’s HDE system if that is something you already use.
>
>  
>
>     The initial release includes everything needed to get a Dynamic AI version 7 installed and running on:
>         Windows 10 Pro 64 bit edition
>         IIS with ISAPI extensions enabled
>
>  
>
>     No license code is necessary for this release - a popup will however alert the user on every login that this is a pre-release Dynamic AI version - not for production use. User=Administrator, PW=nextgen to login as usual. 
>
>  
>
>     There are a number of things you can’t do yet - like most Design actions - listedit save - AI - calendar reports - world maps… and there are a number of things not working - Excel export - PDF - email reports - schedules… and a lot of functionality is not available as in version 6. Carsten did give preview at Synergy of the foundation of how these things will work so there is more actually done in this area than is apparent.
>
>  
>
>     Use latest version Chrome for evaluation for now on Desktop. No special handling for touch / iPad events in the current release - also Mobile view is not prepared. 
>
>  
>
> Details about the March 2017 release:
>
>  
>
> - Dynamic AI version 7 application code (C++ IIS 64bit ISAPI extension)
>
> - Latest HighStock version (release as of 31st March 2017)
>
> - Dynamic AI version 7 client side javascript - un-minified versions of the source.
>
> - Dynamic AI version 7 client side minified css - source SCSS files.
>
>  
>
> Support files for database connectivity “out of the box” without additional installation:
>
> - DB2
>
> - Oracle
>
> - MySQL
>
> - MariaDB
>
> - SQLite
>
> - PostgreSQL
>
> and additionally 2 folders:
>
> - db_drivers\mssql
>
> - db_drivers\msaccess
>
> which are copied onto the machine being installed to - but the “drivers” aren’t installed by default. In our findings we have had scenarios with old office installations where there would be an installation conflict trying to install the Access driver - and we aren’t 100% sure that it is necessary in all cases. The same goes for the ODBC access to MS SQL.
>
> In case the demo doesn’t run the reports - you might have to run the file in the msaccess folder.
>
>  
>
> Best regards,
>
> Bob
>
>  
>
> Robert Cergol
>
> Dynamic AI Product Mgr. / Senior Consultant
>
>  
>
> cid:image003.png@01D02ACB.9AB36480
>
> Direct: 305.234.7030 | bob.cergol@dataaccess.com|
>
> P: 305.238.0012 | DataAccess.com | Facebook | Twitter
>
> Synergy2017EmailSig
>
>  
>
>  
![nocss](https://cloud.githubusercontent.com/assets/4049382/25282461/d63636d4-26b0-11e7-8907-baedb2e4f7d6.png)

**Comment by dwphk** [comment]
I've been able to reproduce this on a fresh Windows 7:
![kepernyofoto 2017-04-21 - du 5 39 47](https://cloud.githubusercontent.com/assets/4049382/25285181/9f6f542e-26b9-11e7-98cf-60394304cf94.png)

**Comment by dwphk** [comment]
Here is the fix, add this 
```xml
    <staticContent>
        <remove fileExtension=".woff" />
        <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
    </staticContent>
```
to web.config. So it should look like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <defaultDocument>
            <files>
                <remove value="iisstart.htm" />
                <remove value="Default.htm" />
                <remove value="Default.asp" />
                <remove value="index.htm" />
            </files>
        </defaultDocument>
        <handlers accessPolicy="Read, Execute, Script">
            <remove name="ISAPI-dll" />
            <add name="ISAPI-dll" path="DynamicAI" verb="*" modules="IsapiModule" scriptProcessor="C:\DynamicAI\bin\dynamic_ai_iis.dll" resourceType="Unspecified" requireAccess="Execute" preCondition="bitness64" />
        </handlers>
    <staticContent>
        <remove fileExtension=".woff" />
        <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
    </staticContent>
    </system.webServer>
</configuration>
```

**Comment by RCergol** [comment]
I confirm that adding that bit of script fixes the problem on my Win10 Pro system.
Thanks,
Bob

**Comment by dwphk** [comment]
I've updated the installer code with the new section.
